// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using alexandria.api.Helpers;

#nullable disable

namespace alexandria.api.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240518203033_AddDeviceTypeFKAndFormatsColumn")]
    partial class AddDeviceTypeFKAndFormatsColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("alexandria.api.Entities.DeviceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EbookDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formats")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePathTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("alexandria.api.Entities.KnownDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EbookDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formats")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePathTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("KnownDevices");
                });

            modelBuilder.Entity("alexandria.api.Entities.KnownDevice", b =>
                {
                    b.HasOne("alexandria.api.Entities.DeviceType", "DeviceType")
                        .WithMany("KnownDevices")
                        .HasForeignKey("DeviceTypeId");

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("alexandria.api.Entities.DeviceType", b =>
                {
                    b.Navigation("KnownDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
